config/routes.rb
Rails.application.routes.draw do
  root 'candidates#search'
  resources :candidates, only: [:index] do
    collection do 
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  validates :city, :technologies, :experience, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def index
    @candidates = Candidates::Filter.new(candidate_params).filter
  end

  def search; end

  private

  def candidate_params
    params.permit(:city, :technology, :experience)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/_alert.html.erb
<% if object.empty? %>
  <div class='alert alert-danger text-center px-2 py-4' role='alert'>
    <%= t('.not_found', name: params[:technology]) %>
  </div>
<% else %>
  <div class='alert alert-success alert-dismissible text-center px-2 py-4 mb-5' role='alert'>
    <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
      <span aria-hidden="true">&times;</span>
    </button>
    <%= t('.found', unity: object.count, name: params[:technology]) %>
  </div>
<% end %>

app/views/candidates/index.html.erb
<div class='container-fluid'>
  <div class='container mt-5'>
    <%= render partial: 'alert', locals: { object: @candidates } %>
    <% @candidates.each do |candidate| %>
      <div class='row mb-4 justify-content-center'>
        <div class='col-sm-8'>
          <div class='card card-hover border border-primary'>
            <div class='card-body'>
              <h5 class='card-title'><%= t('.developer_html', person: candidate.id) %></h5>
              <hr>
              <p class='card-text'>
                <ul>
                  <li><%= t('.place', place: candidate.city) %></li>
                  <li><%= t('.experience', years: candidate.experience) %></li>
                  <li><%= t('.technologies') %>
                   |<% candidate.technologies.each do |tech| %>
                        <%= t('.technology', name: tech['name']) %>
                    <% end %>
                  </li>
                </ul>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/candidates/search.html.erb
<div class='container-fluid'>
  <h1 class='text-center mt-5 mb-5 title'><%= t('.candidates') %></h1>
  <div class='container'>
    <div class='card border border-primary'>
      <h4 class='card-header'><%= t('.search_candidates') %></h4>
      <div class='card-body'>
        <h5 class='card-title text-center mb-5'><%= t('.select_filters') %></h5>
        <%= form_with url: candidates_path, method: :get, local: true do |form| %>
          <div class='row'>
            <div class='col-sm-4 text-center'>
              <%= form.label :city, t('.candidates_from') %>
              <%= form.text_field :city, placeholder: t('.placeholder.city'), class: 'form-control' %>
            </div>
            <div class='col-sm-4 text-center'>
              <%= form.label :technology, t('.to_work_with') %>
              <%= form.text_field :technology, placeholder: t('.placeholder.technology'), class: 'form-control' %>
            </div>
            <div class='col-sm-4 text-center'>
              <%= form.label :experience, t('.those_have') %>
              <%= form.text_field :experience, placeholder: t('.placeholder.experience'), class: 'form-control' %>
            </div>
          </div>
          <div class='row mt-4'>
            <div class='col-sm text-center'>
              <%= form.submit t('.button.search'), class: 'btn btn-outline-secondary px-4 py-2' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('.tech_jobs') %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class='navbar navbar-expand-lg navbar-light'>
      <a class='navbar-brand ml-5' href='http://localhost:3000/'>
        <img src='/assets/company-logo.png' width='200' height='50' alt=''>
      </a>
    </nav>
    <%= yield %>
  </body>
</html>